global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "scheduler-api"
    static_configs:
      - targets: ["scheduler:8211"]
    metrics_path: "/metrics"
    scrape_interval: 30s
